//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::page::Entity as Page;
pub use super::score::Entity as Score;
pub use super::survey::Entity as Survey;
pub use super::user::Entity as User;
